### ISSUE TITLE
SYMBOL_VAR not correctly attached

### ISSUE THREAD

**Issue by HekpoMaH** [acr31/features-javac#10]
### Steps to reproduce:
0. Compile jsoup repository: https://github.com/jhy/jsoup
1. Take https://github.com/jhy/jsoup/blob/a4b5e826f2440b19ee2a98fdece7211433cfdaed/src/test/java/org/jsoup/MultiLocaleRule.java and it's corresponding proto from the feature extractor. 
2. Create the graph for the corresponding proto. You will discover that node 608, corresponding to `oldLocale` usage inside `Locale.setDefault` method call is incorrectly mapped to have SYMBOL_MTH parent.
![image](https://user-images.githubusercontent.com/8327849/73855406-f3d77a00-482b-11ea-820f-ba12a17f18d1.png)
### Desired behaviour

`oldLocale` should be attached to SYMBOL_VAR similar to it's definition:
![image](https://user-images.githubusercontent.com/8327849/73855690-5597e400-482c-11ea-802b-09c9a557df65.png)

**Comment by acr31** [comment]
Hopefully fixed in 276ba87a4f6fc688eac0a9ee99d62bf5b9f7216f - please feel free to reopen if its not.
