### ISSUE TITLE
SYMBOL_TYP incorrectly associated with IDENTIFIER_TOKEN nodes containing method names

### ISSUE THREAD

**Issue by fkrawiec** [acr31/features-javac#11]
Possibly related to #10
[log.txt](https://github.com/acr31/features-javac/files/4162776/log.txt) contains a list of about 300 occurrences of this bug in the current ML4PL corpus.
## Steps to reproduce
Run feature extractor on the [metrics project](https://github.com/dropwizard/metrics) and inspect graph corresponding to [DerivativeGaugeTest.java](https://github.com/dropwizard/metrics/blob/3748f09b249f47a24ef868595fed4556ec5e92b1/metrics-core/src/test/java/com/codahale/metrics/DerivativeGaugeTest.java).
## Expected behaviour
Currently node 293 is associated with SYMBOL_TYP(com.codahale.metrics.DerivativeGaugeTest$1)
![image](https://user-images.githubusercontent.com/22860276/73897345-bbf92280-487d-11ea-8e8d-66ba01eaf64c.png)
This should instead be the appropriate SYMBOL_MTH.

**Comment by acr31** [comment]
Hopefully fixed in 276ba87a4f6fc688eac0a9ee99d62bf5b9f7216f - please feel free to reopen if its not.
