### ISSUE TITLE
Missing proto file when using absolute path. 

### ISSUE THREAD

**Issue by ITWOI** [acr31/features-javac#14]
Hi,

Thanks for the tool. 

I may find a bug in generating proto files.

The following command works fine.

`javac -cp extractor/target/features-javac-extractor-1.0.0-SNAPSHOT-jar-with-dependencies.jar -Xplugin:FeaturePlugin T.java
`

However, the following command can't generate the prote file.

`javac -cp extractor/target/features-javac-extractor-1.0.0-SNAPSHOT-jar-with-dependencies.jar -Xplugin:FeaturePlugin /proj/fff000/modelAbil/features-javac/T.java
`

This is interesting that my working directory is `/proj/fff000/modelAbil/features-javac`.

My jdk version is `javac 11.0.2`

May I ask is it mean

**Comment by acr31** [comment]
Thank you for the report. Do you get an error message? Could you include it here please.

**Comment by ITWOI** [comment]
Here is the output of `javac -cp extractor/target/features-javac-extractor-1.0.0-SNAPSHOT-jar-with-dependencies.jar -Xplugin:FeaturePlugin /proj/fff000/modelAbil/features-javac/T.java`:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/proj/fff000/modelAbil/features-javac/extractor/target/features-javac-extractor-1.0.0-SNAPSHOT-jar-with-dependencies.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

I don't think it is an error message because the correct command gives the same output.

**Comment by acr31** [comment]
Yep. You are right.

I just tried it on my machine: the answer is that it has generated the proto and it's put it in

`/proj/fff000/modelAbil/features-javac/proj/fff000/modelAbil/features-javac/T.java.proto`

I remember now that I have so far failed to implement a satisfactory solution for choosing the output path so at the moment it just uses the whole path of the source file relative to the current directory.

A better solution would be for it to take a directory as a command line parameter and write proto files there in the same way that '-d' works for the main compiler but I've not got around to that.
